'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Plus,RefreshCw,Layers3,Wallet,Activity,Globe2,ArrowUpRight,Trash2,Download,Search,BookOpen} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyContent} from '@/components/ui/empty';
import {calculate,emptyPortfolio,today,type Portfolio,type Trade} from '@/lib/portfolio';
import type {Quote,Chip,Holding,GlobalQuote} from '@/lib/market';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,BarChart,Bar} from 'recharts';
type Source={name:string;updated:number|null;error?:string};
type Overseas=GlobalQuote&{error?:string;updated?:number};
type Observations=Record<string,{chips:Chip[];holdings:Holding[]}>;
const money=(n:number|null|undefined)=>n===null||n===undefined?'—':new Intl.NumberFormat('zh-TW',{maximumFractionDigits:2}).format(n);
const tone=(n:number|null|undefined)=>!n?'':n>0?'positive':'negative';
const signed=(n:number|null|undefined)=>n===null||n===undefined?'—':(n>0?'+':'')+money(n);
async function api(path:string,options?:RequestInit):Promise<any>{const r=await fetch(path,options);const data:any=await r.json();if(!r.ok)throw Object.assign(new Error(data.error||'暫時無法完成，請重試。'),{status:r.status});return data;}
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:string[][];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,n])=><SelectItem value={v} key={v}>{n}</SelectItem>)}</SelectContent></Select>}
function Blank({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <Empty className="empty"><EmptyHeader><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{children}</EmptyDescription></EmptyHeader>{action&&<EmptyContent>{action}</EmptyContent>}</Empty>}
function SourceNotes({items}:{items:Source[]}){return <div className="legend">{items.map(s=><span key={s.name}>{s.name}：{s.error|| (s.updated?'擷取 '+new Date(s.updated).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false}):'尚未取得')}</span>)}</div>}
function PriceChart({data}:{data:{date:string;close:number}[]}){return <div className="chart" aria-label="每日收盤價走勢"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid stroke="#28364a" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>String(v).slice(5)} stroke="#91a4bb" fontSize={12} minTickGap={35}/><YAxis domain={['auto','auto']} stroke="#91a4bb" fontSize={12} width={65}/><Tooltip contentStyle={{background:'#172131',border:'1px solid #41536a',borderRadius:8}} formatter={v=>[money(Number(v)),'收盤價']}/><Line dataKey="close" stroke="#b5ed7f" strokeWidth={2} dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}
const freshTrade=():Trade=>({id:crypto.randomUUID(),date:today(),broker:'新光',symbol:'',name:'',kind:'buy',shares:1000,price:0,fee:0,tax:0,amount:0,note:''});
export default function InvestmentDashboard(){
 const [portfolio,setPortfolio]=useState<Portfolio>(emptyPortfolio),[revision,setRevision]=useState(0),[auth,setAuth]=useState<'loading'|'yes'|'error'>('loading');
 const [quotes,setQuotes]=useState<Quote[]>([]),[index,setIndex]=useState<GlobalQuote|null>(null),[global,setGlobal]=useState<Overseas[]>([]),[sources,setSources]=useState<Source[]>([]),[chipSources,setChipSources]=useState<Source[]>([]);
 const [chips,setChips]=useState<Chip[]>([]),[holders,setHolders]=useState<Holding[]>([]),[observations,setObservations]=useState<Observations>({});
 const [busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState('portfolio'),[broker,setBroker]=useState('all');
 const [trade,setTrade]=useState<Trade|null>(null),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState<string|null>(null),[watchOpen,setWatchOpen]=useState(false),[watchDraft,setWatchDraft]=useState('');
 const [selected,setSelected]=useState('2330'),[detail,setDetail]=useState<string|null>(null),[history,setHistory]=useState<{date:string;close:number}[]>([]),[historySource,setHistorySource]=useState(''),[historyError,setHistoryError]=useState('');
 const quotesBy=useMemo(()=>Object.fromEntries(quotes.map(q=>[q.symbol,q])),[quotes]);
 const allPositions=useMemo(()=>calculate(portfolio.trades),[portfolio]);const positions=allPositions.filter(p=>broker==='all'||p.broker===broker);const held=positions.filter(p=>p.shares>0);
 const missing=held.filter(p=>quotesBy[p.symbol]?.close==null);const marketValue=held.reduce((s,p)=>s+p.shares*(quotesBy[p.symbol]?.close||0),0);const cost=held.reduce((s,p)=>s+p.cost,0);const pnl=missing.length?null:marketValue-cost;
 const realized=positions.reduce((s,p)=>s+p.realized,0),dividends=positions.reduce((s,p)=>s+p.dividends,0);
 const symbols=useMemo(()=>[...new Set([...portfolio.watchlist,...allPositions.filter(p=>p.shares>0).map(p=>p.symbol)])].slice(0,50),[portfolio.watchlist,allPositions]);
 const symbolKey=[...new Set([selected,...symbols])].slice(0,50).join(',');const loadingRef=useRef(false);
 const loadPortfolio=useCallback(async()=>{try{const r=await api('/api/portfolio');setPortfolio(r.portfolio);setRevision(r.revision);setAuth('yes');}catch(e:any){setAuth('error');setError(e.message);}},[]);
 useEffect(()=>{void loadPortfolio();},[loadPortfolio]);
 const loadMarkets=useCallback(async()=>{if(loadingRef.current)return;loadingRef.current=true;setBusy(true);setError('');const results=await Promise.allSettled([api('/api/market?group=quotes').then(r=>{setQuotes(r.quotes);setIndex(r.index);setSources(r.status);}),api('/api/market?group=global').then(r=>setGlobal(r.items))]);const bad=results.find(r=>r.status==='rejected');if(bad?.status==='rejected')setError(bad.reason.message);loadingRef.current=false;setBusy(false);},[]);
 useEffect(()=>{if(auth!=='yes')return;void loadMarkets();const timer=setInterval(()=>{if(document.visibilityState==='visible')void loadMarkets();},3600000);return()=>clearInterval(timer);},[auth,loadMarkets]);
 useEffect(()=>{if(auth!=='yes'||!symbolKey)return;let active=true;api('/api/market?group=chips&symbols='+encodeURIComponent(symbolKey)).then(r=>{if(active){setChips(r.chips);setHolders(r.holdings);setObservations(r.observations);setChipSources(r.status);}}).catch(e=>{if(active)setChipSources([{name:'籌碼',updated:null,error:e.message}]);});return()=>{active=false;};},[auth,symbolKey,busy]);
 useEffect(()=>{if(!detail)return;let active=true;setHistory([]);setHistoryError('');api('/api/market?group=history&symbol='+detail+'&market='+encodeURIComponent(quotesBy[detail]?.market||'上市')).then(r=>{if(active){setHistory(r.data||[]);setHistorySource(r.source);if(r.error)setHistoryError(r.error);}}).catch(e=>{if(active)setHistoryError(e.message);});return()=>{active=false;};},[detail,quotesBy]);
 async function mutate(input:Record<string,unknown>){setSaving(true);try{const r=await api('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,revision})});setPortfolio(r.portfolio);setRevision(r.revision);setNotice('已儲存');return r;}finally{setSaving(false);}}
 async function saveTrade(e:React.FormEvent){e.preventDefault();setFormError('');try{await mutate({action:'add',trade});setTrade(null);}catch(e:any){setFormError(e.message);}}
 function openTrade(){setFormError('');setTrade(freshTrade());}
 async function saveWatch(e:React.FormEvent){e.preventDefault();setFormError('');try{await mutate({action:'watch',symbols:watchDraft.split(/[\s,，]+/).filter(Boolean)});setWatchOpen(false);}catch(e:any){setFormError(e.message);}}
 function download(){const payload={exportedAt:new Date().toISOString(),version:1,...portfolio};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chipfolio-'+today()+'.json';a.click();URL.revokeObjectURL(url);}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();for(const tool of [{name:'read_portfolio',title:'讀取投資庫存',description:'讀取畫面中的交易紀錄與持股，金額為台幣。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('不接受參數');if(auth!=='yes')throw new Error('請先等候本機資料讀取完成');return {portfolio,positions:allPositions};}},{name:'start_trade_entry',title:'開啟交易表單',description:'開啟新增交易表單；不會儲存或下單。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('不接受參數');if(auth!=='yes')throw new Error('請先等候本機資料讀取完成');openTrade();return {status:'form_opened'};}}]){try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[portfolio,allPositions,auth]);
 const importRef=useRef<HTMLInputElement>(null);
 async function importBackup(file?:File){if(!file)return;try{if(file.size>4000000)throw new Error('備份超過 4 MB。');const backup=JSON.parse(await file.text());await mutate({action:'import',backup});setNotice('已合併匯入本機；相同交易不會重複新增。');}catch(e:any){setError(e.message);}finally{if(importRef.current)importRef.current.value='';}}
 const chosen=selected||symbols[0];const h=holders.find(x=>x.symbol===chosen);const c=chips.find(x=>x.symbol===chosen);const obs=observations[chosen];const prior=obs?.holdings.filter(x=>x.date<(h?.date||'')).at(-1);const rolling=obs?.chips||[];
 const topMarkets=[index,global.find(x=>x.symbol==='TX'),global.find(x=>x.symbol==='^SOX'),global.find(x=>x.symbol==='TSM')];
 return <><header className="topbar"><a href="/" className="brand" style={{textDecoration:'none'}}><Layers3/>Chipfolio<small>盤後投資筆記</small></a><span>本機儲存 · 不需帳號 · 台灣時間</span></header><main><div className="heading"><div><p className="eyebrow">AFTER THE CLOSE</p><h1>我的投資總覽</h1><p>台股庫存・法人籌碼・半導體隔夜市場</p></div><div className="actions"><button className="button secondary" onClick={()=>void loadMarkets()} disabled={busy||auth!=='yes'}><RefreshCw size={16}/>{busy?'資料更新中…':'更新資料'}</button><button className="button" onClick={openTrade} disabled={auth!=='yes'}><Plus size={16}/>新增交易</button></div></div>
 {auth==='loading'&&<p role="status">正在讀取你的投資紀錄…</p>}{error&&<div className="error" role="alert">{error} <button className="linkbutton" onClick={()=>void loadPortfolio()}>重新讀取</button></div>}{notice&&<p role="status" style={{color:'#b5ed7f'}}>{notice}</p>}
 <section className="markets">{['加權指數','台指期夜盤','費城半導體 SOX','台積電 ADR'].map((name,i)=>{const q=topMarkets[i];return <article key={name}><span>{name}</span><strong>{money(q?.close)}</strong><div className={tone(q?.pct)}>{q?.pct!=null?signed(q.pct)+'%':'—'}</div><small>{q?.date||'尚未取得資料'} {i>1?'美東收盤':i===1?'交易歸屬日':'收盤'}</small></article>;})}</section>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="navtabs"><TabsTrigger value="portfolio"><Wallet/>我的資產</TabsTrigger><TabsTrigger value="chips"><Activity/>籌碼觀察</TabsTrigger><TabsTrigger value="global"><Globe2/>隔夜市場</TabsTrigger></TabsList>
 <TabsContent value="portfolio"><div className="pillrow">{['all','新光','中信'].map(b=><button key={b} className={'pill '+(broker===b?'active':'')} onClick={()=>setBroker(b)}>{b==='all'?'全部帳戶':b+'證券'}</button>)}</div><section className="stats">{[['庫存市值',missing.length?null:marketValue,missing.length?`${missing.length} 檔缺收盤價，暫不合計`:'依各股最新收盤價'],['未實現損益',pnl,cost&&pnl!=null? signed(pnl/cost*100)+'% · 含買進費用':'持股市值減剩餘成本'],['已實現損益',realized,'含賣出手續費與交易稅'],['累計股息',dividends,'依實際入帳金額']].map(([name,n,hint])=><article key={String(name)}><span>{name}</span><strong className={name==='未實現損益'||name==='已實現損益'?tone(n as number):''}>{n==null?'—':'NT$ '+money(n as number)}</strong><small>{hint}</small></article>)}</section>
 <section className="panel"><div className="panelhead"><h2>我的持股 <small>{held.length} 筆部位</small></h2><span>以股為單位 · 移動平均成本</span></div>{!held.length?<Blank title="從第一筆交易開始" action={<button className="button" disabled={auth!=='yes'} onClick={openTrade}><Plus size={16}/>新增交易</button>}>記錄買進日期、股數與價格，把新光和中信的投資放在一起。</Blank>:<Table><TableHeader><TableRow>{['股票／券商','持有股數','平均成本','收盤價／日期','庫存市值','未實現損益'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{held.map(p=>{const q=quotesBy[p.symbol];const value=q?.close==null?null:p.shares*q.close;const profit=value==null?null:value-p.cost;return <TableRow key={p.broker+p.symbol}><TableCell><button className="linkbutton rowname" onClick={()=>setDetail(p.symbol)}>{p.symbol} {q?.name||p.name}</button><small style={{display:'block'}}>{p.broker}</small></TableCell><TableCell>{money(p.shares)}</TableCell><TableCell>{money(p.cost/p.shares)}</TableCell><TableCell>{money(q?.close)}<small style={{display:'block'}}>{q?.date||'缺資料'}</small></TableCell><TableCell>{money(value)}</TableCell><TableCell className={tone(profit)}>{signed(profit)}<small style={{display:'block'}}>{profit!=null&&p.cost?signed(profit/p.cost*100)+'%':''}</small></TableCell></TableRow>;})}</TableBody></Table>}</section>
 <section className="panel"><div className="panelhead"><h2>自選觀察</h2><button className="linkbutton" disabled={auth!=='yes'} onClick={()=>{setWatchDraft(portfolio.watchlist.join(', '));setFormError('');setWatchOpen(true);}}>管理自選</button></div><Table><TableHeader><TableRow>{['股票','收盤價','漲跌','成交量（張）','資料日期','外資買賣超（張）'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{portfolio.watchlist.map(s=>{const q=quotesBy[s];const chip=chips.find(x=>x.symbol===s);return <TableRow key={s}><TableCell><button className="linkbutton" onClick={()=>setDetail(s)}>{s} {q?.name||''}</button></TableCell><TableCell>{money(q?.close)}</TableCell><TableCell className={tone(q?.change)}>{signed(q?.change)}</TableCell><TableCell>{q?.volume==null?'—':money(q.volume/1000)}</TableCell><TableCell>{q?.date||'待取得'}</TableCell><TableCell className={tone(chip?.foreign)}>{chip?.foreign==null?'—':signed(chip.foreign/1000)}<small style={{display:'block'}}>{chip?.date}</small></TableCell></TableRow>;})}</TableBody></Table>{!portfolio.watchlist.length&&<p className="panelbody">尚無自選股票。</p>}</section>
 <section className="panel"><div className="panelhead"><h2>交易紀錄</h2><div className="actions"><input ref={importRef} type="file" accept=".json,application/json" style={{display:'none'}} aria-label="匯入 Chipfolio 備份" onChange={e=>void importBackup(e.target.files?.[0])}/><button className="button secondary" disabled={saving||auth!=='yes'} onClick={()=>importRef.current?.click()}>匯入備份（合併）</button><button className="button secondary" onClick={download} disabled={auth!=='yes'}><Download size={15}/>匯出備份</button></div></div>{!portfolio.trades.length?<p className="panelbody muted">尚無交易紀錄。</p>:<Table><TableHeader><TableRow>{['日期／券商','股票','類型','股數 × 價格／股息','費用／稅','操作'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{[...portfolio.trades].reverse().filter(t=>broker==='all'||t.broker===broker).map(t=><TableRow key={t.id}><TableCell>{t.date}<small style={{display:'block'}}>{t.broker}</small></TableCell><TableCell>{t.symbol} {t.name}<small style={{display:'block',maxWidth:200,whiteSpace:'normal'}}>{t.note}</small></TableCell><TableCell><span className="badge">{{buy:'買進',sell:'賣出',dividend:'股息'}[t.kind]}</span></TableCell><TableCell>{t.kind==='dividend'?'NT$ '+money(t.amount):money(t.shares)+' × '+money(t.price)}</TableCell><TableCell>{money(t.fee)} / {money(t.tax)}</TableCell><TableCell><button className="linkbutton" aria-label={'刪除 '+t.date+' '+t.symbol+' 交易'} onClick={()=>setDeleting(t.id)}><Trash2 size={16}/></button></TableCell></TableRow>)}</TableBody></Table>}</section><p className="note">成本採移動平均法，費用請依券商實收填寫；賣出損益與股息分開列示。股票分割、減資、配股尚不自動調整，發生時請先核對庫存。損益估值不預扣未來賣出費用。</p><SourceNotes items={sources}/></TabsContent>
 <TabsContent value="chips"><div className="heading"><div><h2>持股背後的籌碼</h2><p>法人以股數統計換算為張；大戶以每週持股分布觀察。</p></div><div style={{minWidth:200}}><Choice value={chosen} onChange={setSelected} label="選擇籌碼股票" items={[...new Set([chosen,...symbols])].map(s=>[s,s+' '+(quotesBy[s]?.name||'')])}/></div></div><section className="stats">{[['外資',c?.foreign],['投信',c?.trust],['自營商',c?.dealer]].map(([label,n])=><article key={String(label)}><span>{label}買賣超</span><strong className={tone(n as number)}>{n==null?'—':signed(Number(n)/1000)} <small>張</small></strong><small>{c?.date||'尚無資料'}</small></article>)}<article><span>1,000 張以上持股</span><strong>{h?money(h.over1000)+'%':'—'}</strong><small>{h?.date||'尚無資料'} · 週資料</small></article></section><div className="grid2"><section className="panel"><div className="panelhead"><h2>法人累積觀察</h2><span>已保存 {rolling.length} 個交易日</span></div><div className="panelbody">{rolling.length>1?<div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={rolling.slice(-20).map(r=>({...r,foreign:(r.foreign||0)/1000,trust:(r.trust||0)/1000,dealer:(r.dealer||0)/1000}))}><CartesianGrid stroke="#28364a" vertical={false}/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} stroke="#91a4bb" fontSize={12}/><YAxis stroke="#91a4bb" fontSize={12}/><Tooltip contentStyle={{background:'#172131',border:'1px solid #41536a'}}/><Bar name="外資（張）" dataKey="foreign" fill="#8cafeb"/><Bar name="投信（張）" dataKey="trust" fill="#b5ed7f"/><Bar name="自營商（張）" dataKey="dealer" fill="#c3a5ec"/></BarChart></ResponsiveContainer></div>:<Blank title="開始累積法人紀錄">每次更新會保存最新交易日；累積兩天後顯示比較圖，不補造歷史數據。</Blank>}<div className="list">{[5,20].map(days=>{const rows=rolling.slice(-days);return <div key={days}><span>最近 {days} 筆紀錄・外資合計</span><span>{rows.length===days?signed(rows.reduce((s,r)=>s+(r.foreign||0),0)/1000)+' 張':`資料不足（${rows.length}/${days}）`}</span></div>;})}</div></div></section><section className="panel"><div className="panelhead"><h2>大戶持股分布</h2><span>{h?.date||'尚未取得'}</span></div><div className="panelbody list">{[['400 張以上',h?.over400,prior?.over400],['1,000 張以上',h?.over1000,prior?.over1000]].map(([label,current,previous])=><div key={String(label)}><span>{label}</span><span>{current==null?'—':money(Number(current))+'%'}<small style={{display:'block'}}>{previous==null?'待累積前期資料':'較 '+prior?.date+' '+signed(Number(current)-Number(previous))+' 個百分點'}</small></span></div>)}<div><span>股東人數（1–15 級合計）</span><b>{h?money(h.holders):'—'}</b></div><p className="note">400 張以上含 1,000 張以上，兩者不可相加。持股分布變化可能受股本及持有人跨級影響，不能直接等同大戶買賣量。</p><a href="https://www.tdcc.com.tw/portal/zh/smWeb/qryStock" target="_blank" rel="noreferrer" className="linkbutton">查看集保官方歷史資料 ↗</a></div></section></div><SourceNotes items={chipSources}/></TabsContent>
 <TabsContent value="global"><div className="heading"><div><h2>隔夜市場觀察</h2><p>美股顯示已結束的交易日；夜盤以期交所公布資料為準。</p></div><span className="badge">不推算隔日漲跌</span></div><div className="grid2">{global.map(g=><section className="panel" key={g.symbol}><div className="panelhead"><h2>{g.name}</h2><span>{g.symbol}</span></div><div className="panelbody"><div style={{display:'flex',alignItems:'baseline',gap:18,marginBottom:18}}><strong style={{fontSize:30}}>{money(g.close)}</strong><span className={tone(g.pct)}>{g.pct!=null?signed(g.pct)+'%':'—'}</span><small>{g.date||'尚未取得'}</small></div>{g.history&&<PriceChart data={g.history}/>}<p className="note">{g.detail}</p>{g.error&&<p className="error">{g.error}</p>}{g.url&&<a className="linkbutton" href={g.url} target="_blank" rel="noreferrer">{g.source} <ArrowUpRight size={14} style={{display:'inline'}}/></a>}</div></section>)}</div>{!global.length&&<Blank title={busy?'正在讀取隔夜市場…':'尚無隔夜資料'}>更新資料即可查詢。</Blank>}<p className="note">海外資料使用 Yahoo Finance 的非官方介面，可能延遲或暫停服務。台指期漲跌基準為官方參考價，並非「較當天下午現貨收盤」；夜盤交易歸屬日也不等於開盤日。請以各卡片日期核對。</p></TabsContent></Tabs>
 <footer><span>CHIPFOLIO · 盤後投資筆記</span><span>開啟頁面時自動查詢，每小時檢查一次 · 集保快取 12 小時</span></footer></main>
 <Dialog open={!!trade} onOpenChange={v=>{if(!v&&!saving)setTrade(null);}}><DialogContent><DialogHeader><DialogTitle>新增交易紀錄</DialogTitle><DialogDescription>手動記帳，不會向券商下單。1 張 = 1,000 股。</DialogDescription></DialogHeader>{trade&&<form onSubmit={saveTrade} className="formgrid"><label>券商<Choice value={trade.broker} onChange={v=>setTrade({...trade,broker:v as Trade['broker']})} items={['新光','中信'].map(v=>[v,v+'證券'])} label="券商"/></label><label>類型<Choice value={trade.kind} onChange={v=>setTrade({...trade,kind:v as Trade['kind']})} items={[["buy","買進"],["sell","賣出"],["dividend","股息入帳"]]} label="交易類型"/></label><label>日期<input required type="date" value={trade.date} max={today()} onChange={e=>setTrade({...trade,date:e.target.value})}/></label><label>股票代號<input required placeholder="例如 2330" value={trade.symbol} maxLength={7} onChange={e=>{const symbol=e.target.value.toUpperCase().trim();setTrade({...trade,symbol,name:quotesBy[symbol]?.name||''});}}/></label><label className="wide">股票名稱<input required value={trade.name} maxLength={40} onChange={e=>setTrade({...trade,name:e.target.value})}/></label>{trade.kind==='dividend'?<label className="wide">實際入帳股息（元）<input type="number" min="0.01" step="0.01" required value={trade.amount||''} onChange={e=>setTrade({...trade,amount:Number(e.target.value)})}/></label>:<><label>股數<input type="number" min="1" step="1" max="10000000" required value={trade.shares||''} onChange={e=>setTrade({...trade,shares:Number(e.target.value)})}/></label><label>成交單價（元）<input type="number" min="0.0001" step="0.0001" required value={trade.price||''} onChange={e=>setTrade({...trade,price:Number(e.target.value)})}/></label><label>實收手續費（元）<input type="number" min="0" step="0.01" required value={trade.fee} onChange={e=>setTrade({...trade,fee:Number(e.target.value)})}/></label>{trade.kind==='sell'&&<label>實收交易稅（元）<input type="number" min="0" step="0.01" required value={trade.tax} onChange={e=>setTrade({...trade,tax:Number(e.target.value)})}/></label>}</>}<label className="wide">備註（選填）<input value={trade.note} maxLength={300} onChange={e=>setTrade({...trade,note:e.target.value})}/></label><p className="wide note">{trade.kind==='dividend'?'請填扣除代扣費用後的實際入帳金額。':'成交金額 NT$ '+money(trade.shares*trade.price)+'；費用與交易稅請依券商實際金額填寫，預設 0 元。'}</p>{formError&&<div className="wide error" role="alert">{formError}</div>}<button type="submit" disabled={saving} className="button wide">{saving?'儲存中…':'儲存交易'}</button></form>}</DialogContent></Dialog>
 <Dialog open={watchOpen} onOpenChange={v=>{if(!saving)setWatchOpen(v);}}><DialogContent><DialogHeader><DialogTitle>管理自選股票</DialogTitle><DialogDescription>用逗號或空格分隔台股代號，最多 50 檔。預設清單是觀察標的，不代表你的持股。</DialogDescription></DialogHeader><form onSubmit={saveWatch}><label>股票代號<input value={watchDraft} onChange={e=>setWatchDraft(e.target.value.toUpperCase())}/></label>{formError&&<p className="error">{formError}</p>}<button className="button" style={{marginTop:18}} disabled={saving}>儲存自選</button></form></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!saving)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>刪除這筆交易？</AlertDialogTitle><AlertDialogDescription>會重新計算庫存與損益。若刪除後造成賣出超過持股，系統會保留原紀錄。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={saving}>取消</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={async e=>{e.preventDefault();try{await mutate({action:'delete',id:deleting});setDeleting(null);}catch(e:any){setError(e.message);setDeleting(null);}}}>確認刪除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><DialogContent className="sm:max-w-3xl"><DialogHeader><DialogTitle>{detail} {detail&&quotesBy[detail]?.name} · 收盤走勢</DialogTitle><DialogDescription>未還原日線，除權息或分割可能造成價格跳動。</DialogDescription></DialogHeader>{history.length?<PriceChart data={history}/>:<p>{historyError||'正在讀取歷史收盤價…'}</p>}{historyError&&history.length>0&&<p className="error">{historyError}</p>}<small>{historySource} · {history[0]?.date} — {history.at(-1)?.date}</small><button className="button secondary" onClick={()=>{if(detail)setSelected(detail);setTab('chips');setDetail(null);}}>查看這檔股票的籌碼</button></DialogContent></Dialog>
 </>;
}
