import {useCallback,useEffect,useState} from 'react';
import {ComposedChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,ReferenceLine} from 'recharts';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {MarketChart} from './market-chart';
import type {IndexIntraday} from '../lib/index-data';
import type {Candle} from '../lib/market';
import type {LiveIndex} from '../lib/live-index';
type Result<T>={data:T|null;updated:number|null;checked:number;error?:string};
async function get<T>(group:string):Promise<Result<T>>{const r=await fetch('/api/market?group='+group);if(!r.ok)throw new Error('暫時無法取得指數圖表。');return r.json();}
const format=(v:number|undefined|null)=>v==null?'—':v.toLocaleString('zh-TW',{maximumFractionDigits:2});
const taipeiTime=(t:number)=>new Date(t).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour12:false});
export function IndexChart({quote,onClose}:{quote:LiveIndex|null;onClose:()=>void}){
 const [view,setView]=useState('intraday'),[intraday,setIntraday]=useState<Result<IndexIntraday>|null>(null),[daily,setDaily]=useState<Result<Candle[]>|null>(null),[dailyBusy,setDailyBusy]=useState(false),[chartError,setChartError]=useState(''),[dailyError,setDailyError]=useState('');
 const load=useCallback(async()=>{try{setIntraday(await get<IndexIntraday>('index-intraday'));setChartError('');}catch(e){setChartError(e instanceof Error?e.message:'無法讀取分時資料。');}},[]);
 const loadDaily=useCallback(async(force=false)=>{setDailyBusy(true);setDailyError('');try{setDaily(await get<Candle[]>('index-daily'+(force?'&refresh=1':'')));}catch(e){setDailyError(e instanceof Error?e.message:'無法讀取日線資料。');}finally{setDailyBusy(false);}},[]);
 useEffect(()=>{if(view!=='intraday')return;void load();const refresh=()=>{if(document.visibilityState==='visible')void load();};const timer=setInterval(refresh,15000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh);};},[load,view]);
 useEffect(()=>{if(view==='daily'&&!daily&&!dailyBusy&&!dailyError)void loadDaily();},[view,daily,dailyBusy,dailyError,loadDaily]);
 const d=intraday?.data;const latest=d?.points.at(-1);const sameDay=quote?.date===d?.date;const previous=sameDay?quote?.previous:d?.previous;const points=d?.points||[];const maxAmount=Math.max(...points.map(p=>p.amount||0),1);const prices=points.map(p=>p.close);if(previous!=null)prices.push(previous);const lo=Math.min(...prices),hi=Math.max(...prices),margin=Math.max((hi-lo)*.08,1);const start=d?Date.parse(d.date+'T09:00:00+08:00'):0,end=d?Date.parse(d.date+'T13:35:00+08:00'):0;
 const rows=daily?.data||[];const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const provisional=quote?.date===today&&quote.open!=null&&quote.high!=null&&quote.low!=null?{date:quote.date,open:quote.open,high:quote.high,low:quote.low,close:quote.close}:null;
 const dayRows=provisional?[...rows.filter(r=>r.date!==provisional.date),provisional]:rows;
 return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="sm:max-w-5xl"><DialogHeader><DialogTitle>加權指數 · 市場走勢</DialogTitle><DialogDescription>證交所 MIS 當日分時及證交所歷史日線。免費來源可能延遲，請核對報價日期。</DialogDescription></DialogHeader><div className="actions"><button className={'pill '+(view==='intraday'?'active':'')} aria-pressed={view==='intraday'} onClick={()=>setView('intraday')}>盤中走勢</button><button className={'pill '+(view==='daily'?'active':'')} aria-pressed={view==='daily'} onClick={()=>setView('daily')}>歷史 K 線／收盤走勢</button><button className="pill" disabled={dailyBusy} onClick={()=>{if(view==='intraday')void load();else void loadDaily(true);}}>重新查詢</button></div>
 {view==='intraday'?<>{(chartError||intraday?.error)&&<p className="error" role="alert">{chartError||intraday?.error}</p>}{d?<><div className="actions"><span>{d.date} · 最新分時 {latest?.time}</span><strong>{format(latest?.close)}</strong><small>昨收 {format(previous)} · 今日分時最高 {format(Math.max(...points.map(p=>p.close)))}／最低 {format(Math.min(...points.map(p=>p.close)))}</small></div><div style={{height:300,minWidth:0}}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={points} margin={{top:15,right:12,bottom:15,left:5}}><CartesianGrid stroke="#e5e5ea" vertical={false}/><XAxis dataKey="timestamp" type="number" domain={[start,end]} ticks={[start,start+3600000,start+7200000,start+10800000,start+16200000]} tickFormatter={t=>taipeiTime(Number(t)).slice(0,5)} stroke="#86868b" fontSize={12}/><YAxis yAxisId="price" domain={[lo-margin,hi+margin]} tickFormatter={v=>format(Number(v))} stroke="#86868b" width={75} fontSize={12}/><Tooltip content={({active,payload,label})=>active&&payload?.length?<div style={{background:'#ffffff',border:'1px solid rgba(0,0,0,.1)',padding:12,borderRadius:8,color:'#1d1d1f'}}><strong>{taipeiTime(Number(label))}</strong><div>指數 {format(payload[0].payload.close)}</div><div>分段成交金額 {format(payload[0].payload.amount)} 億元</div></div>:null}/>{previous!=null&&<ReferenceLine yAxisId="price" y={previous} stroke="#86868b" strokeDasharray="5 5" label={{value:'昨收',fill:'#86868b',position:'insideTopRight'}}/>}<Line yAxisId="price" dataKey="close" stroke="#0071e3" strokeWidth={2} dot={points.length===1} activeDot={{r:4}} isAnimationActive={false} connectNulls={false}/></ComposedChart></ResponsiveContainer></div><div style={{overflowX:'auto'}}><svg viewBox="0 0 900 105" style={{width:'100%',minWidth:560,display:'block'}} role="img" aria-label="當日分段成交金額，單位億元"><text x={80} y={14} fill="#86868b" fontSize={12}>分段成交金額（億元）</text>{points.map(p=><rect key={p.timestamp} x={80+(p.timestamp-start)/(end-start)*805-1.5} y={80-(p.amount||0)/maxAmount*55} width={3} height={(p.amount||0)/maxAmount*55} fill="#0071e3"><title>{p.time} {format(p.amount)} 億元</title></rect>)}{[start,start+3600000,start+7200000,start+10800000,start+16200000].map(t=><text key={t} x={80+(t-start)/(end-start)*805} y={100} textAnchor="middle" fill="#86868b" fontSize={12}>{taipeiTime(t).slice(0,5)}</text>)}</svg></div><small>{intraday?.checked?'上次查詢 '+taipeiTime(intraday.checked):'尚未查詢'} · {points.length} 筆</small><p className="note">藍色柱為分段成交金額（非股數）；非交易日顯示最近交易日資料。</p></>:<p>{chartError||intraday?.error||'正在載入當日走勢…'}</p>}</>:<>{dailyBusy&&<p role="status">正在取得官方歷史日線…</p>}{(dailyError||daily?.error)&&<p className="error">{dailyError||daily?.error}</p>}{dayRows.length>0&&<MarketChart data={dayRows}/>}<small>載入近六個月歷史，之後查詢會存在本機；無成交量資料。</small>{provisional&&<p className="note">今日 K 棒使用 MIS 的當日開、高、低與最新指數，尚未以官方盤後日線確認，會隨報價更新。</p>}</>}
 </DialogContent></Dialog>;
}
