import {useMemo,useState} from 'react';
import type {Candle} from '../lib/market';
import {aggregateCandles,withMovingAverages,type ChartPeriod} from '../lib/chart-utils';
const maColors={ma5:'#ff9500',ma20:'#5e5ce6',ma60:'#af52de'};
const format=(v:number|undefined)=>v==null?'—':v.toLocaleString('zh-TW',{maximumFractionDigits:2});
export function MarketChart({data}:{data:Candle[]}){
 const [mode,setMode]=useState('candles'),[period,setPeriod]=useState<ChartPeriod>('day'),[range,setRange]=useState(60),[offset,setOffset]=useState(0),[hover,setHover]=useState<number|null>(null),[mas,setMas]=useState(true),[volume,setVolume]=useState(true);
 const all=useMemo(()=>withMovingAverages(aggregateCandles(data,period)),[data,period]);const count=Math.min(range||all.length,all.length),start=Math.max(0,all.length-count-Math.min(offset,Math.max(0,all.length-count)));const rows=all.slice(start,start+count);const selected=hover==null?rows.length-1:Math.min(hover,rows.length-1);const active=rows[selected];
 const hasVolume=all.some(r=>r.volume!=null),showVolume=volume&&hasVolume;
 const width=900,pad=64,priceTop=20,priceBottom=270,height=showVolume?400:325;const prices=rows.flatMap(r=>[r.low,r.high,...(mas?[r.ma5,r.ma20,r.ma60].filter((v):v is number=>v!=null):[])]);const low=Math.min(...prices),high=Math.max(...prices),margin=Math.max((high-low)*.08,Math.abs(high)*.001,.1);const y=(v:number)=>priceBottom-(v-low+margin)/(high-low+margin*2)*(priceBottom-priceTop),step=(width-pad*2)/Math.max(rows.length,1),x=(i:number)=>pad+(i+.5)*step;const maxVol=Math.max(...rows.map(r=>r.volume||0),1);
 const select=(clientX:number,element:SVGSVGElement)=>{const bounds=element.getBoundingClientRect();const position=(clientX-bounds.left)/bounds.width*width;setHover(Math.max(0,Math.min(rows.length-1,Math.floor((position-pad)/step))));};
 const changePeriod=(p:ChartPeriod)=>{setPeriod(p);setOffset(0);setHover(null);};
 return <div className="market-chart" style={{minWidth:0}}><div className="actions" style={{marginBottom:12}}><div className="actions" role="group" aria-label="圖表類型">{[['candles','K 線'],['line','收盤走勢']].map(([v,label])=><button key={v} className={'pill '+(mode===v?'active':'')} aria-pressed={mode===v} onClick={()=>setMode(v)}>{label}</button>)}</div><div className="actions" role="group" aria-label="K 線週期">{(['day','week','month'] as const).map((p,i)=><button key={p} className={'pill '+(period===p?'active':'')} aria-pressed={period===p} onClick={()=>changePeriod(p)}>{['日','週','月'][i]}</button>)}</div></div>
 <div className="actions" style={{marginBottom:12}}>{[[20,'20 筆'],[60,'60 筆'],[120,'120 筆'],[0,'全部']].map(([n,label])=><button key={n} className={'pill '+(range===n?'active':'')} aria-pressed={range===n} onClick={()=>{setRange(Number(n));setOffset(0);setHover(null);}}>{label}</button>)}<button className="pill" disabled={rows.length<=10} aria-label="放大圖表" onClick={()=>{setRange(Math.max(10,Math.floor((range||all.length)*.7)));setHover(null);}}>＋</button><button className="pill" disabled={rows.length>=all.length} aria-label="縮小圖表" onClick={()=>{setRange(Math.min(all.length,Math.ceil((range||all.length)*1.4)));setHover(null);}}>－</button><button className="pill" onClick={()=>{setRange(60);setOffset(0);setHover(null);}}>回到最新</button></div>
 <div className="actions" style={{marginBottom:10}}><label><input type="checkbox" checked={mas} onChange={e=>setMas(e.target.checked)} style={{width:'auto'}}/> 均線</label><label><input type="checkbox" disabled={!hasVolume} checked={showVolume} onChange={e=>setVolume(e.target.checked)} style={{width:'auto'}}/> {hasVolume?'成交量':'來源未提供成交量'}</label>{mas&&Object.entries(maColors).map(([key,color])=><small key={key} style={{color}}>{key.toUpperCase()} {format(active?.[key as keyof typeof maColors])}</small>)}</div>
 {!rows.length?<p>尚無完整開高低收資料。</p>:<><p style={{minHeight:42}}>{active?.date} · 開 {format(active?.open)}　高 {format(active?.high)}　低 {format(active?.low)}　收 {format(active?.close)}{active?.volume!=null?' · 成交量 '+format(active.volume):''}{active?.contract?' · 合約 '+active.contract:''}</p><div style={{overflowX:'auto'}}><svg viewBox={`0 0 ${width} ${height}`} style={{width:'100%',minWidth:560,display:'block'}} tabIndex={0} role="img" aria-label="價格圖表，左右方向鍵或點選可查看價格" onPointerMove={e=>select(e.clientX,e.currentTarget)} onPointerDown={e=>select(e.clientX,e.currentTarget)} onPointerLeave={()=>setHover(null)} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setHover(Math.max(0,Math.min(rows.length-1,selected+(e.key==='ArrowLeft'?-1:1))));}}}>
 {[0,1,2,3,4].map(i=>{const value=low-margin+(high-low+margin*2)*i/4;return <g key={i}><line x1={pad} x2={width-pad} y1={y(value)} y2={y(value)} stroke="#e5e5ea"/><text x={5} y={y(value)+4} fill="#86868b" fontSize={12}>{format(value)}</text></g>;})}
 {mode==='line'?<polyline points={rows.map((r,i)=>`${x(i)},${y(r.close)}`).join(' ')} stroke="#0071e3" fill="none" strokeWidth={2}/>:rows.map((r,i)=>{const color=r.close>=r.open?'#ff3b30':'#34c759';return <g key={r.date}><line x1={x(i)} x2={x(i)} y1={y(r.high)} y2={y(r.low)} stroke={color}/><rect x={x(i)-Math.min(step*.65,18)/2} y={Math.min(y(r.open),y(r.close))} width={Math.min(step*.65,18)} height={Math.max(Math.abs(y(r.open)-y(r.close)),1.5)} fill={color}/></g>;})}
 {mas&&Object.entries(maColors).map(([key,color])=><polyline key={key} points={rows.flatMap((r,i)=>r[key as keyof typeof maColors]==null?[]:[`${x(i)},${y(r[key as keyof typeof maColors]!)}`]).join(' ')} fill="none" stroke={color} strokeWidth={1.5}/>)}
 {showVolume&&<><line x1={pad} x2={width-pad} y1={310} y2={310} stroke="#e5e5ea"/><text x={pad} y={305} fill="#86868b" fontSize={11}>{rows.some(r=>r.volume!=null)?'成交量（來源單位）':'此來源未提供成交量'}</text>{rows.map((r,i)=>r.volume==null?null:<rect key={r.date} x={x(i)-Math.min(step*.65,18)/2} y={370-r.volume/maxVol*50} width={Math.min(step*.65,18)} height={r.volume/maxVol*50} fill={r.close>=r.open?'#ff3b30':'#34c759'} opacity={.7}/>)}</>}
 {rows.map((r,i)=>(i===0||i===rows.length-1||i%Math.ceil(rows.length/5)===0)?<text key={r.date} x={x(i)} y={height-10} textAnchor="middle" fill="#86868b" fontSize={12}>{r.date}</text>:null)}
 {active&&<g><line x1={x(selected)} x2={x(selected)} y1={priceTop} y2={height-25} stroke="#86868b" strokeDasharray="4 4"/><line x1={pad} x2={width-pad} y1={y(active.close)} y2={y(active.close)} stroke="#86868b" strokeDasharray="4 4"/><circle cx={x(selected)} cy={y(active.close)} r={3} fill="#0071e3"/></g>}
 </svg></div>{all.length>count&&<label style={{display:'block',marginTop:10}}>瀏覽歷史 <input type="range" min={0} max={all.length-count} value={start} aria-label="移動圖表時間範圍" onChange={e=>{setOffset(all.length-count-Number(e.target.value));setHover(null);}}/></label>}<small>{rows[0]?.date} — {rows.at(-1)?.date} · 顯示 {rows.length}／{all.length} 筆{period!=='day'?' · 最後一根可能尚未完成':''}</small></>}
 <p className="note">未還原價格 · 紅漲綠跌 · 均線資料不足時不顯示。</p></div>;
}
