import {cached,database} from './storage';
export type Quote={symbol:string;name:string;close:number|null;change:number|null;volume:number|null;date:string;market:string};
export type Chip={symbol:string;date:string;foreign:number|null;trust:number|null;dealer:number|null};
export type Holding={symbol:string;date:string;over400:number;over1000:number;holders:number};
export type GlobalQuote={symbol:string;name:string;close:number|null;pct:number|null;date:string;source:string;url:string;detail?:string;history?:{date:string;close:number}[]};
export function num(v:unknown):number|null{if(v===null||v===undefined)return null;const s=String(v).replace(/[,\s%]/g,'');if(!s||s==='--'||s==='-'||s==='NULL')return null;const n=Number(s);return Number.isFinite(n)?n:null;}
export function iso(v:string){const s=v.replace(/\D/g,'');const year=s.length===7?Number(s.slice(0,3))+1911:Number(s.slice(0,4));return `${year}-${s.slice(-4,-2)}-${s.slice(-2)}`;}
async function json(url:string):Promise<any>{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Chipfolio/1.0 personal after-market dashboard'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
const hour=3600000;
export async function twse(){return cached('twse-v2',hour,async()=>{
 const d=await json('https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&type=ALLBUT0999');const table=d.tables?.find((t:any)=>t.fields?.[0]==='證券代號');if(!table?.data?.length||!d.date)throw new Error('上市行情欄位缺漏');
 const date=iso(d.date);const quotes:Quote[]=table.data.map((r:string[])=>({symbol:r[0],name:r[1].trim(),volume:num(r[2]),close:num(r[8]),change:num(r[10])===null?null:(String(r[9]).includes('-')?-1:1)*Number(num(r[10])),date,market:'上市'}));
 const index=d.tables[0]?.data?.find((r:string[])=>r[0]==='發行量加權股價指數');return {quotes,index:index?{symbol:'TAIEX',name:'加權指數',close:num(index[1]),pct:num(index[4]),date,source:'臺灣證券交易所',url:'https://www.twse.com.tw/zh/trading/historical/mi-index.html'} as GlobalQuote:null};
 });}
export async function tpex(){return cached('tpex-v1',hour,async()=>{const d=await json('https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes');if(!Array.isArray(d)||!d[0]?.Date)throw new Error('上櫃行情欄位缺漏');return d.map((r:any):Quote=>({symbol:r.SecuritiesCompanyCode,name:r.CompanyName,close:num(r.Close),change:num(r.Change),volume:num(r.TradingShares),date:iso(r.Date),market:'上櫃'}));});}
export async function institutions(){return cached('institutions-v1',hour,async()=>{const d=await json('https://www.twse.com.tw/fund/T86?response=json&selectType=ALLBUT0999');if(d.stat!=='OK'||!d.data?.length)throw new Error('法人資料未公布');return d.data.map((r:string[]):Chip=>({symbol:r[0],date:iso(d.date),foreign:num(r[4]),trust:num(r[10]),dealer:num(r[11])}));});}
export async function otcInstitutions(){return cached('otc-institutions-v1',hour,async()=>{const d=await json('https://www.tpex.org.tw/openapi/v1/tpex_3insti_daily_trading');if(!Array.isArray(d)||!d[0]?.Date)throw new Error('上櫃法人資料未公布');return d.map((r:any):Chip=>({symbol:r.SecuritiesCompanyCode,date:iso(r.Date),foreign:num(r['Foreign Investors include Mainland Area Investors (Foreign Dealers excluded)-Difference']),trust:num(r['SecuritiesInvestmentTrustCompanies-Difference']),dealer:num(r['Dealers-Difference'])}));});}
export async function holdings(){return cached('tdcc-v2',12*hour,async()=>{const d=await json('https://openapi.tdcc.com.tw/v1/opendata/1-5');if(!Array.isArray(d)||!d.length)throw new Error('集保資料缺漏');const out:Record<string,Holding>={};for(const r of d){const symbol=String(r['證券代號']).trim();const level=Number(r['持股分級']);const date=iso(r['資料日期']||r['\uFEFF資料日期']||'');if(date.startsWith('0-'))throw new Error('集保日期缺漏');const h=out[symbol]??={symbol,date,over400:0,over1000:0,holders:0};if(level>=12&&level<=15)h.over400+=num(r['占集保庫存數比例%'])??0;if(level===15)h.over1000=num(r['占集保庫存數比例%'])??0;if(level>=1&&level<=15)h.holders+=num(r['人數'])??0;}return Object.values(out);});}
export async function futures(){return cached('tx-night-v1',hour,async()=>{const d=await json('https://openapi.taifex.com.tw/v1/DailyMarketReportFut');if(!Array.isArray(d))throw new Error('夜盤資料格式錯誤');const rows=d.filter((r:any)=>r.Contract==='TX'&&r.TradingSession==='盤後'&&/^\d{6}$/.test(r['ContractMonth(Week)'])&&num(r.Last)!==null).sort((a:any,b:any)=>b.Date.localeCompare(a.Date)||a['ContractMonth(Week)'].localeCompare(b['ContractMonth(Week)']));const r=rows[0];if(!r)throw new Error('夜盤收盤尚未公布');return {symbol:'TX',name:'台指期夜盤',close:num(r.Last),pct:num(r['%']),date:iso(r.Date),source:'臺灣期貨交易所',url:'https://www.taifex.com.tw/cht/3/futDailyMarketReport',detail:`${r['ContractMonth(Week)']} 合約；日期為交易歸屬日，漲跌依官方參考價。`} as GlobalQuote;});}
export const overseas=[['^SOX','費城半導體 SOX'],['^NDX','Nasdaq 100'],['TSM','台積電 ADR'],['NVDA','NVIDIA'],['AMD','AMD'],['AVGO','Broadcom']];
export async function usQuote(symbol:string,name:string){return cached('us-v2:'+symbol,hour,async()=>{
 const data=await json(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=3mo&interval=1d`);const d=data.chart?.result?.[0];if(!d?.timestamp?.length)throw new Error('海外資料未取得');const tz='America/New_York';const day=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'});const nyDate=day.format(new Date());const nyHour=Number(new Intl.DateTimeFormat('en-US',{timeZone:tz,hour:'2-digit',hourCycle:'h23'}).format(new Date()));
 const history=d.timestamp.map((t:number,i:number)=>({date:day.format(new Date(t*1000)),close:d.indicators.quote[0].close[i]})).filter((r:any)=>typeof r.close==='number'&&Number.isFinite(r.close)&&(r.date<nyDate||(r.date===nyDate&&nyHour>=17)));
 if(history.length<2)throw new Error('已完成日線不足');const last=history.at(-1),prev=history.at(-2);return {symbol,name,close:last.close,pct:(last.close/prev.close-1)*100,date:last.date,source:'Yahoo Finance（非官方介面）',url:`https://finance.yahoo.com/quote/${encodeURIComponent(symbol)}/`,detail:'美東日期；排除尚未結束的當日交易，收盤後一小時納入。',history} as GlobalQuote;
 });}
export async function stockHistory(symbol:string,market:string){return cached('price-history:'+symbol,hour,async()=>{
 if(market==='上市'){const now=new Date();const months=[new Date(now.getFullYear(),now.getMonth()-1,1),new Date(now.getFullYear(),now.getMonth(),1)];const arrays=[];for(const m of months){const ds=`${m.getFullYear()}${String(m.getMonth()+1).padStart(2,'0')}01`;const d=await json(`https://www.twse.com.tw/exchangeReport/STOCK_DAY?response=json&date=${ds}&stockNo=${symbol}`);if(d.stat==='OK')arrays.push(...d.data.map((r:string[])=>({date:iso(r[0]),close:num(r[6])})));}if(!arrays.length)throw new Error('尚無歷史行情');return arrays.filter(r=>r.close!==null);}
 const d=await json(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}.TWO?range=3mo&interval=1d`);const r=d.chart?.result?.[0];if(!r?.timestamp)throw new Error('尚無上櫃歷史行情');const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'});const today=day.format(new Date());return r.timestamp.map((t:number,i:number)=>({date:day.format(new Date(t*1000)),close:r.indicators.quote[0].close[i]})).filter((p:any)=>typeof p.close==='number'&&p.date<today);
 });}
export async function recordObservations(chips:Chip[],holders:Holding[]){const db=database();const symbols=[...new Set([...chips.map(x=>x.symbol),...holders.map(x=>x.symbol)])];const result:Record<string,{chips:Chip[];holdings:Holding[]}>={};for(const symbol of symbols){const key='observations:'+symbol;const old=await db.prepare('SELECT payload FROM market_cache WHERE key=?').bind(key).first<{payload:string}>();const data=old?JSON.parse(old.payload):{chips:[],holdings:[]};for(const [field,item] of [['chips',chips.find(x=>x.symbol===symbol)],['holdings',holders.find(x=>x.symbol===symbol)]] as const){if(item){data[field]=[...data[field].filter((r:any)=>r.date!==item.date),item].sort((a:any,b:any)=>a.date.localeCompare(b.date)).slice(-80);}}await db.prepare('INSERT INTO market_cache(key,payload,updated) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET payload=excluded.payload,updated=excluded.updated').bind(key,JSON.stringify(data),Date.now()).run();result[symbol]=data;}return result;}

